name: SAST
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  boost_security_sast:
    name: Boost Security / Native Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Native Scanner
        uses: peaudecastor/boost-security-scanner-github@v2
        env:
          BOOST_CLI_URL: https://assets.build.boostsecurity.io
        with:
          action: scan
          api_endpoint: https://devel.boostsecurity.dev
          api_token: ${{ secrets.BOOST_API_TOKEN_DEV }}
          additional_args: --disable-telemetry --api-version v2
          cli_version: 3.0.0.rc483
          scanner_version: 3.0.0.rc483
